version: '3.8'

services:
  # --- 1. POSTGRESQL ---
  postgres:
    image: postgres:15-alpine
    container_name: military_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: military_db
      POSTGRES_USER: military_user      # <--- Використовуємо те, що в Java
      POSTGRES_PASSWORD: military_password      # <--- Використовуємо те, що в Java
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d military_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- 2. REDIS (На одному рівні з postgres, а не всередині!) ---
  redis:
    image: redis:7-alpine
    container_name: military_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data_v2:
    driver: local